### ISSUE TITLE
Running examples

### ISSUE THREAD

**Issue by hwborchers** [SudoWodo/StochOptim#7]
As JCNash has pointed out, this does not work. In `test.R`, I assume the last line should be okay, but isn't. What is the error here?

    final_ans <- GlobalWrapper(fn      = rastrigin, 
                               lower   = lb,
                               upper   = ub, 
                               method  = "DEoptim", 
                               control = ctrl1)
    ## Error in LocalWrapperDEoptim(fn = fn, lower = lower, upper = upper,
    method = method,  : 
    object 'DEoptimWrapper' not found

We could distinguish between TESTS and EXAMPLES. The tests are parts of the package and check that user input errors are recognized and handled correctly.

For your mentors you should provide working examples that can be run without errors and show that solvers return meaningful results - and allow discussions on forms of input and output.

So what you call "UserWorkFlow" is in my eyes the `examples.R` page with code that could, e.g., become later part of a vignette.

**Comment by SudoWodo** [comment]
I should also add these lines in the file as they are essential to run the code in `test.R`

**Comment by SudoWodo** [comment]
Agreed.
